### ISSUE TITLE
Retrainng with new dataset and generating frozen_inference.pb model file

### ISSUE THREAD

**Issue by NiranjanAntany** [yinguobing/head-pose-estimation#12]
Hi,

I am working in your eye-lid detection algorithm which uses tensor-flow library. i was stuck in a procedure how to retrain the algorithm with new face and landmark annotated data-set. I have tried with procedure given in tensor-flow and able to get frozen_inference.pb file. but while loading it in your algorithm am getting below error.
---------------------------------------------------------------------------------------------------------
KeyError: "The name 'logits/BiasAdd:0' refers to a Tensor which does not exist. The operation, 'logits/BiasAdd', does not exist in the graph."

-----------------------------------------------------------------------------------------------------
Please help me in the procedure how to retrain with new face data-set and get the frozen_inference,pb file.

Kindly do the needful..

Regards,
Niranjan B

**Comment by yinguobing** [comment]
The name  'logits/BiasAdd:0' refers to a node of the original model's output, that consists all the landmarks' location. If you have replaced the model with your own, please remember to replace it with the node name you used.

To retrain with new data set, try following these [posts](https://yinguobing.com/deeplearning/) (in Chinese).

**Comment by NiranjanAntany** [comment]
Hello,

Thank you for your Support. i have Studied your Article and trying to retrain the Landmark detection with opensource data set. I have downloaded (300VW , IBUG & LFPW )Data set. The data set contains .JPG images and .pts files. now am stuck at How to generate TFRecord file with available data set.., Should i want to convert .pts to .CSV..? Pls help me how to generated TFrecord file..?

Regards,
Niranjan B

**Comment by yinguobing** [comment]
Hi Niranjan, for parsing `pts` file, check this out:
https://github.com/yinguobing/image_utility/blob/master/pts_tools.py

For generating tfrecord file, refer to this one:
https://github.com/yinguobing/tfrecord_utility/tree/ibug

**Comment by NiranjanAntany** [comment]
Hi,
Thanks for you support,

I have generated the data.csv for the data-sets (300VW , IBUG & LFPW). Now i need to generate the "train.record, test.record and validation.record" when i tried to run the python script generate_tfrecord.py . its taking json files..but i have only .pts and images with me..Please help me how to generate json file from .pts..
(https://github.com/yinguobing/tfrecord_utility/blob/ibug/generate_tfrecord.py)

And it could be very helpful that you can suggest some opensource landmark Annotation tool for annotating all 68 points for my new data-set... i was doing this as my internship project..

Kindly help me in this..

Regards,
Niranjan B

**Comment by yinguobing** [comment]
Hi Niranjan,

Before generating the tfrecord file, you have to make sure the data is clean and ready to be used. Since you are asking about the json file, I assume you have not processed the image and points for later usage.

The points to be used later need to be normalized, according to the input image of face area. Please check this out for detailed explanation:
https://yinguobing.com/facial-landmark-localization-by-deep-learning-preprocessing/

Good luck!

**Comment by yinguobing** [comment]
For the second question, try this annotation tool: https://www.landmarker.io

**Comment by NiranjanAntany** [comment]
Hi Yinguobing,
Thanks for your help..

Now i can able to generate the .json for my datasets. and also generated .csv file for train, test and validate.. and executed the python script **generate_tf_recore.tf.py** and got train.record, valid.record and test.record files.

but when i tried to view my test.record file using **view_record.py** am getting following error.
-------------------------------------------------------------------------------------------------------------
python3 view_record.py 
2019-03-13 19:25:03.542523: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-13 19:25:03.567346: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label/points.  Can't parse serialized Example.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn

---------------------------------------------------------------------------------------------------------------
 and also please help me how to generate the **freeze_inference.pb** file from my test.record. for landmark detection..

Kindly help me..

Regards,
Niranjan B

**Comment by yinguobing** [comment]
So you have successfully generated the tfrecord file? Congratulations! :+1: 

The error message is saying it can not find the value of a dict by the key of "label/points", which should be put in the record by [this line of code](https://github.com/yinguobing/tfrecord_utility/blob/cb5f4d06e3bb15dc27ffd27edc03ef06101fdf83/generate_tfrecord.py#L77).  You can manually print out all of the keys in a tensorflow example, and check if this key-value pair exists.

To export a model for inference, try following [this post](https://yinguobing.com/facial-landmark-localization-by-deep-learning-save-model-application/).

**Comment by vamsichevikala** [comment]
Hi,

i followed the steps given in this issue and in section Part VI mentioned in this  [link](https://yinguobing.com/deeplearning/)

after generating the train.record, test.record and validation.record. I am running the code
 `python3 /cnn-facial-landmark-master/landmark.py.` 
and getting the following error.

tensorflow.python.framework.errors_impl.InvalidArgumentError: Feature: label/marks (data type: float) is required but could not be found.

kindly suggest your input on this feature and how to solve the error.

**Comment by yinguobing** [comment]
@vamsichevikala The code was updated and the running command has changed. Make sure you are using the latest code.
