### ISSUE TITLE
how can I solve the error?

### ISSUE THREAD

**Issue by KimYonghyun94** [yinguobing/head-pose-estimation#33]
OpenCV version: 3.3.1
Linux is fine! Python multiprocessing works.
OpenCV Error: Unspecified error (FAILED: fs.is_open(). Can't open "assets/deploy.prototxt") in ReadProtoFromTextFile, file /io/opencv/modules/dnn/src/caffe/caffe_io.cpp, line 1113
Traceback (most recent call last):
  File "/content/head-pose-estimation/estimate_head_pose.py", line 161, in <module>
    main()
  File "/content/head-pose-estimation/estimate_head_pose.py", line 57, in main
    mark_detector = MarkDetector()
  File "/content/head-pose-estimation/mark_detector.py", line 68, in __init__
    self.face_detector = FaceDetector()
  File "/content/head-pose-estimation/mark_detector.py", line 14, in __init__
    self.face_net = cv2.dnn.readNetFromCaffe(dnn_proto_text, dnn_model)
cv2.error: /io/opencv/modules/dnn/src/caffe/caffe_io.cpp:1113: error: (-2) FAILED: fs.is_open(). Can't open "assets/deploy.prototxt" in function ReadProtoFromTextFile

Could you help me?

**Comment by yinguobing** [comment]
Please make sure the file exist.

KimYonghyun94 <notifications@github.com>于2020年7月2日 周四下午7:34写道：

**Comment by KimYonghyun94** [comment]
all files are exist. I am using 'Google Colab'.
I dont know why this error...

**Comment by yinguobing** [comment]
There is no need to use Colab. Follow the instructions in the README file, please.

**Comment by KimYonghyun94** [comment]
Really thank you for reply 
I fixed all error but I have one question
How i save the videofile instead of immediately
When i runtime this code
''  python3 Estimate_head_pose.py --video video.mp4  ''
 playing immediately but i need to save the files...

I really appreciate to you

**Comment by yinguobing** [comment]
You need `cv2.VideoWriter` to do that. The branch `write_video` can be of help.

**Comment by KimYonghyun94** [comment]
thank you so much~ have a good day~

2020년 7월 7일 (화) 오후 5:04, Yin Guobing <notifications@github.com>님이 작성:

**Comment by KevinTsaiCodes** [comment]
I have the same problem

**Comment by yinguobing** [comment]
@KevinTsaiCodes Please make sure all files tracked by Git are not modified in any way.
