### ISSUE TITLE
IndexError: list index (0) out of range

### ISSUE THREAD

**Issue by youjinChung** [yinguobing/head-pose-estimation#38]
Hello Yinguobing,

I was working on your former version of the repo and when I updated my virtual environment for the latest repo. The former one doesn't work anymore. I need to figure out why, but wanted to ask you if you have a clue with the error.
```
Traceback (most recent call last):
  File "estimate_head_pose.py", line 190, in <module>
    main()
  File "estimate_head_pose.py", line 66, in main
    mark_detector = MarkDetector()
  File "/Users/EUGENE/Documents/ADAS/HP/mark_detector.py", line 75, in __init__
    self.model = keras.models.load_model(saved_model)
  File "/Users/EUGENE/Documents/ADAS/HP/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 212, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/Users/EUGENE/Documents/ADAS/HP/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 130, in load
    _read_legacy_metadata(object_graph_def, metadata)
  File "/Users/EUGENE/Documents/ADAS/HP/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 179, in _read_legacy_metadata
    node_paths = _generate_object_paths(object_graph_def)
  File "/Users/EUGENE/Documents/ADAS/HP/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 204, in _generate_object_paths
    for reference in object_graph_def.nodes[current_node].children:
IndexError: list index (0) out of range
```
I checked the model files' locations and seems it gets right.

-Youjin

**Comment by youjinChung** [comment]
I succeed to run with the latest repo, so close this issue.

**Comment by yinguobing** [comment]
Good to know that!
