### ISSUE TITLE
Error reading SavedModel

### ISSUE THREAD

**Issue by janoskaz** [yinguobing/head-pose-estimation#51]
OS: Windows 11 Pro
python: 3.10.9
tensorflow: 2.12.0
openCV: 4.7.0.72

When running `python main.py --cam 0` (or any command), I get fllowing error:

`Traceback (most recent call last):
  File "C:\Users\test\python\head_pose_estimation\main.py", line 49, in <module>
    mark_detector = MarkDetector()
  File "C:\Users\test\python\head_pose_estimation\mark_detector.py", line 75, in __init__
    self.model = keras.models.load_model(saved_model)
  File "C:\Users\test\AppData\Local\r-miniconda\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\test\AppData\Local\r-miniconda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\test\AppData\Local\r-miniconda\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 703, in is_directory_v2
    return _pywrap_file_io.IsDirectory(compat.path_to_bytes(path))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 47: invalid continuation byte`

There seems to be problem when reading `saved_model.pb or files in `variables folder`.` Re-downloading the file does not help.

**Comment by yinguobing** [comment]
A quick guess is version mismatch of TensorFlow. Could you please try TF2.3 instead?

**Comment by janoskaz** [comment]
Thanks, downgrading Tensorflow helped. It is working up to version 2.10 of TF.
